from microbit import *
import music

display.show(Image.MUSIC_QUAVER)
while True:
    music.play('g4:2')
    music.play('g4:2')
    music.play('g4:2')
    music.play('g4:2')

    music.play('g4:2')
    music.play('e4:2')
    music.play('g4:2')
    music.play('e4:2')
    music.play('g4:2')
    music.play('e4:2')
    music.play('c4:4')
    music.play('d4:2')
    music.play('f4:2')

    music.play('e4:2')
    music.play('d4:2')
    music.play('g4:4')
    music.play('e4:4')
    music.play('g4:2')
    music.play('e4:2')
    music.play('g4:2')
    music.play('e4:2')
    music.play('g4:2')

    music.play('e4:2')
    music.play('c4:4')
    music.play('d4:2')
    music.play('f4:2')
    music.play('e4:2')
    music.play('d4:2')
    music.play('c4:4')
    music.play('e4:4')
    music.play('d4:2')

    music.play('d4:2')
    music.play('f4:2')
    music.play('f4:2')
    music.play('e4:2')
    music.play('c4:2')
    music.play('g4:4')
    music.play('d4:2')
    music.play('f4:2')
    music.play('e4:2')

    music.play('d4:2')
    music.play('g4:2')
    music.play('e4:2')
    music.play('g4:2')
    music.play('e4:2')
    music.play('g4:4')
    music.play('e4:2')
    music.play('g4:2')
    music.play('e4:2')

    music.play('c4:2')
    music.play('d4:2')
    music.play('f4:2')
    music.play('e4:2')
    music.play('d4:2')
    music.play('c4:4')
